### ISSUE TITLE
ChatRoomHandler.java" not found!

### ISSUE THREAD

**Issue by lyg00702** [jpush/jmessage-phonegap-plugin#100]
**WARNING: 如果不按照这个表格，我们将无法帮助你，并将忽略你的问题。**

## 你的运行环境 Red Hat 4.8.5-16

* 插件版本: 
* 平台（Android / iOS）:Android
* Cordova version (```cordova -v```):8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```):android@7.1.4
* Ionic Version (if using Ionic)

## 期望效果

告诉我们你希望达到什么效果。

## 实际效果

安装插件报错：
```
Error during processing of action! Attempting to revert...
Failed to install 'jmessage-phonegap-plugin': CordovaError: Uh oh!
"/home/cordovaprj_v2/hello02/plugins/jmessage-phonegap-plugin/src/android/ChatRoomHandler.java" not found!
    at copyFile (/home/cordovaprj_v2/hello02/platforms/android/cordova/lib/pluginHandlers.js:219:36)
    at copyNewFile (/home/cordovaprj_v2/hello02/platforms/android/cordova/lib/pluginHandlers.js:247:5)
```
## 重现步骤

  1. ...
  2. ...
  3. ...
  4. ...

## 背景

你尝试做过些什么？
在win10 环境，一样的命令没有报错，可以正常安装插件

## Debug logs

包括 Android 或 iOS 的日志：

  * iOS: XCode logs
  * Android: $ adb logcat / Android Studio logcat

**Comment by lyg00702** [comment]
detail message:
```
Error during processing of action! Attempting to revert...
Failed to install 'jmessage-phonegap-plugin': CordovaError: Uh oh!
"/home/cordova_pj/hello/plugins/jmessage-phonegap-plugin/src/android/ChatRoomHandler.java" not found!
    at copyFile (/home/cordova_pj/hello/platforms/android/cordova/lib/pluginHandlers.js:233:36)
    at copyNewFile (/home/cordova_pj/hello/platforms/android/cordova/lib/pluginHandlers.js:261:5)
    at install (/home/cordova_pj/hello/platforms/android/cordova/lib/pluginHandlers.js:43:17)
    at ActionStack.process (/home/cordova_pj/hello/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/cordova_pj/hello/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/home/cordova_pj/hello/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /home/cordova_pj/hello/platforms/android/cordova/Api.js:247:74
    at _fulfilled (/home/cordova_pj/hello/platforms/android/cordova/node_modules/q/q.js:834:54)
    at /home/cordova_pj/hello/platforms/android/cordova/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/cordova_pj/hello/platforms/android/cordova/node_modules/q/q.js:796:13)

```
